import type { Metadata } from "next";
import { Container, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import "@/app/ui/globals.css";
import NavBar from "./NavBar";
import { inter } from "@/app/ui/fonts";
import Footer from "./Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Theme>
          <Container size="4">
            <NavBar />
            {children}
            <Footer />
          </Container>
        </Theme>
      </body>
    </html>
  );
}
